export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_FULFILLED = 'GET_MOVIES_FULFILLED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_REJECTED = 'GET_MOVIES_REJECTED';

export const GET_MOVIES_BY_ID = "GET_MOVIES_BY_ID";
export const GET_MOVIES_BY_ID_SUCCESS = "GET_MOVIES_BY_ID_SUCCESS";
export const GET_MOVIES_BY_ID_REJECTED = "GET_MOVIES_BY_ID_REJECTED";

export const GET_TV_SHOWS = "GET_TV_SHOWS";
export const GET_TV_SHOWS_SUCCESS = "GET_TV_SHOWS_SUCCESS";
export const GET_TV_SHOWS_REJECTED = "GET_TV_SHOWS_REJECTED";