export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_FULFILLED = 'GET_MOVIES_FULFILLED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_REJECTED = 'GET_MOVIES_REJECTED';

export const GET_MOVIES_BY_ID = "GET_MOVIES_BY_ID";
export const GET_MOVIES_BY_ID_SUCCESS = "GET_MOVIES_BY_ID_SUCCESS";
export const GET_MOVIES_BY_ID_REJECTED = "GET_MOVIES_BY_ID_REJECTED";

export const GET_TV_SHOWS = "GET_TV_SHOWS";
export const GET_TV_SHOWS_SUCCESS = "GET_TV_SHOWS_SUCCESS";
export const GET_TV_SHOWS_REJECTED = "GET_TV_SHOWS_REJECTED";

export const FILTER_MOVIES = "FILTER_MOVIES";
export const FILTER_MOVIES_SUCCESS = "FILTER_MOVIES_SUCCESS";
export const FILTER_MOVIES_REJECTED = "FILTER_MOVIES_REJECTED";

export const FETCH_NEXT_PREV_MOVIES = "FETCH_NEXT_PREV_MOVIES";
export const FETCH_NEXT_PREV_MOVIES_SUCCESS="FETCH_NEXT_PREV_MOVIES_SUCCESS";
export const FETCH_NEXT_PREV_MOVIES_REJECTED= "FETCH_NEXT_PREV_MOVIES_REJECTED";